### ISSUE TITLE
Handling duplicately named vtile source layers / Ability to filter features on source

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#20]
Compositing vtiles requires a decision on how to handle layer names within and across vtiles that might clash or be duplicates. The current plan is to allow duplicate names / render everything, but allow calling applications to differentiate (say for styling) the features that come from `mapnik::vector::tile_datasource`.

So, two vtiles composted together that both have a `buildings` layer but come from difference tile sources could be differentiated like:

```css
#buildings {
  [source='data-virginia'] {
     polygon-fill:red;
  }
  [source='data-DC'] {
     polygon-fill:blue;
  }
}
```

Where `source` or some other magic attribute keyword would report the name of the vtile as originally passed to the compositing code:

```
var sources = [{name:'data-virginia',source:vtA},{name:'data-DC',source:vtB}
```
